#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Classify
* Classify Custom Image Recognition Service
*
* The version of the OpenAPI document: 1.0.0
* Contact: info@inoven.ai
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInlineObject
@end

@interface OAIInlineObject : OAIObject


@property(nonatomic) NSString* imageUrl;

@property(nonatomic) NSString* tag;

@property(nonatomic) NSString* modelId;

@end
